/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 mona.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/mona.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow geometry={nodes.Roof.geometry} material={materials.PaletteMaterial001} position={[-1.381, 0.236, 0.496]} scale={0.679} />
      <mesh castShadow geometry={nodes.Windows.geometry} material={materials.PaletteMaterial002} position={[-1.381, -0.081, 0.496]} scale={0.679} />
      <mesh geometry={nodes.Walls_Inside.geometry} material={materials.Walls} position={[-1.517, 2.345, -7.976]} rotation={[Math.PI, 0, Math.PI]} scale={0.01} />
      <mesh receiveShadow geometry={nodes.Floor_Inside.geometry} material={materials.Floor} position={[-1.517, 0.3, -3.088]} scale={0.01} />
      <mesh geometry={nodes.Walls_Inside001.geometry} material={materials.PaletteMaterial003} position={[-1.517, 0.324, -6.774]} />
      <mesh geometry={nodes.Lamp_008.geometry} material={materials.PaletteMaterial004} position={[3.593, 4.182, 9.795]} />
      <mesh geometry={nodes.Lamp_006001.geometry} material={materials.PaletteMaterial005} position={[12.313, 4.282, -10.376]} />
      <instancedMesh args={[nodes.Mesh033.geometry, materials.PaletteMaterial002, 7]} instanceMatrix={nodes.Mesh033.instanceMatrix} />
      <instancedMesh args={[nodes.Mesh033_1.geometry, materials.PaletteMaterial004, 7]} instanceMatrix={nodes.Mesh033_1.instanceMatrix} />
      <instancedMesh args={[nodes.Mesh045.geometry, materials.PaletteMaterial002, 7]} instanceMatrix={nodes.Mesh045.instanceMatrix} />
      <instancedMesh args={[nodes.Mesh045_1.geometry, materials.PaletteMaterial004, 7]} instanceMatrix={nodes.Mesh045_1.instanceMatrix} />
      <instancedMesh args={[nodes.Puff_Barcelona_002.geometry, materials.PaletteMaterial003, 5]} instanceMatrix={nodes.Puff_Barcelona_002.instanceMatrix} />
      <instancedMesh args={[nodes.Puff_Barcelona_002_1.geometry, materials['Puff barcelona couro'], 5]} instanceMatrix={nodes.Puff_Barcelona_002_1.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/mona.glb')
