/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 ModernArtT.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ModernArtT.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Floor001.geometry} material={materials['Concrete Glossy']} position={[11.186, 0.034, -4.882]} />
      <mesh geometry={nodes.Glass_Roof004.geometry} material={materials['Old Metal white']} position={[10.845, 3.817, -17.824]} />
      <mesh geometry={nodes.Glass004.geometry} material={materials.Glass} position={[10.845, 3.84, -17.824]} />
      <group position={[12.045, 0.034, -2.624]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Plane008.geometry} material={materials.Plaster} />
        <mesh geometry={nodes.Plane008_1.geometry} material={materials['Painted drywall']} />
      </group>
      <mesh geometry={nodes.Outer_Walls006.geometry} material={materials['Dark metal']} position={[12.045, 0.034, -2.624]} rotation={[0, 1.571, 0]} />
      <mesh geometry={nodes.SHC_Modern_Procedural_Art001.geometry} material={materials['Procedural art.003']} position={[-6.043, 1.438, -10.374]} scale={1.873} />
      <mesh geometry={nodes.Modern_Glossy_Artpiece001.geometry} material={materials['Mirror material']} position={[4.69, 0.773, 2.484]} scale={1.895} />
      <mesh geometry={nodes.Bench021.geometry} material={materials['Glossy white']} position={[4.545, 0.327, 2.496]} rotation={[-Math.PI, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Plane006.geometry, materials['Old Metal white'], 16]} instanceMatrix={nodes.Plane006.instanceMatrix} />
      <instancedMesh args={[nodes.Plane007.geometry, materials['Old Metal white'], 16]} instanceMatrix={nodes.Plane007.instanceMatrix} />
      <instancedMesh args={[nodes.Plane071.geometry, materials['Glossy white'], 12]} instanceMatrix={nodes.Plane071.instanceMatrix} />
      <instancedMesh args={[nodes.Circle002.geometry, materials['Dark metal'], 82]} instanceMatrix={nodes.Circle002.instanceMatrix} />
      <instancedMesh args={[nodes.Circle001.geometry, materials['Glossy white'], 92]} instanceMatrix={nodes.Circle001.instanceMatrix} />
      <instancedMesh args={[nodes.Circle001_1.geometry, materials['Dark metal'], 92]} instanceMatrix={nodes.Circle001_1.instanceMatrix} />
      <instancedMesh args={[nodes.Circle001_2.geometry, materials.Light, 92]} instanceMatrix={nodes.Circle001_2.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/ModernArtT.glb')
