/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 mona.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useLoader } from '@react-three/fiber'
import { TextureLoader } from 'three'
import * as THREE from 'three'

export function Model( props ) {
  const { nodes, materials } = useGLTF( '/mona.glb' )


  return (
    <group {...props} dispose={null} onPointerDown={( e ) => e.stopPropagation()}
      onPointerMove={( e ) => e.stopPropagation()} >

      <mesh geometry={nodes.Windows.geometry} material={materials.PaletteMaterial002} position={[-1.381, -0.081, 0.496]} scale={0.679} />

      <mesh geometry={nodes.Floor_Inside.geometry} material={materials.Floor} position={[-1.517, 0.3, -3.088]} scale={0.01} >
      </mesh>
     
      <mesh geometry={nodes.Lamp_008.geometry} material={materials.PaletteMaterial004} position={[3.593, 4.182, 9.795]} />
      <mesh geometry={nodes.Lamp_006001.geometry} material={materials.PaletteMaterial005} position={[12.313, 4.282, -10.376]} />
      <instancedMesh args={[nodes.Mesh033.geometry, materials.PaletteMaterial002, 7]} instanceMatrix={nodes.Mesh033.instanceMatrix} />
      <instancedMesh args={[nodes.Mesh033_1.geometry, materials.PaletteMaterial004, 7]} instanceMatrix={nodes.Mesh033_1.instanceMatrix} />
      <instancedMesh args={[nodes.Mesh045.geometry, materials.PaletteMaterial002, 7]} instanceMatrix={nodes.Mesh045.instanceMatrix} />
      <instancedMesh args={[nodes.Mesh045_1.geometry, materials.PaletteMaterial004, 7]} instanceMatrix={nodes.Mesh045_1.instanceMatrix} />
      <instancedMesh args={[nodes.Puff_Barcelona_002.geometry, materials.PaletteMaterial003, 5]} instanceMatrix={nodes.Puff_Barcelona_002.instanceMatrix} />
      <instancedMesh args={[nodes.Puff_Barcelona_002_1.geometry, materials['Puff barcelona couro'], 5]} instanceMatrix={nodes.Puff_Barcelona_002_1.instanceMatrix} />
    </group>
  )
}

useGLTF.preload( '/mona.glb' )
